---
apiVersion: "logging.openshift.io/v1"
kind: "Elasticsearch"
metadata:
  name: "elasticsearch"
  annotations:
      elasticsearch.openshift.io/loglevel: trace
spec:
  managementState: "Managed"
  nodeSpec:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
  nodes:
  - nodeCount: 3
    roles:
    - client
    - data
    - master
    storage:
      storageClassName: gp2
      size: 10G
  redundancyPolicy: SingleRedundancy
  indexManagement:
    policies:
    - name: infra-policy
      pollInterval: 30m
      phases:
        hot:
          actions:
            rollover:
              maxAge: 2m
        delete:
          minAge: 5m
    mappings:
    - name:  infra
      policyRef: infra-policy
      aliases:
      - infra
      - logs.infra
